### ISSUE TITLE
Image invert_yaxis shifts the plot after upgrading panel library

### ISSUE THREAD

**Issue by rafgonsi** [holoviz/holoviews#4668]
#### ALL software version info
Python 3.7
holoviews==1.13.5
bokeh==2.2.3
panel==0.10.1

#### Description of expected behavior and the observed behavior
The `Image` is shifted after using `invert_yaxis`. The problem appeared after upgrading panel from 0.9.7 to 0.10.1.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
import holoviews as hv
import panel as pn
hv.extension('bokeh')

vector = np.arange(100)
data = np.outer(vector, vector)

hv.Image(data).opts(invert_yaxis=True)

```

#### Screenshots or screencasts of the bug in action
![invert_axis](https://user-images.githubusercontent.com/33317987/97593611-25b7ee80-1a02-11eb-9e31-e1b052ef2cef.gif)

**Comment by analog-cbarber** [comment]
Here is another variant. Note that the third line with a single Panel row containing both orientations is broken in the same way using 0.9.7.

```python
import holoviews as hv
import panel as pn
import numpy as np
from IPython.display import display

hv.extension('bokeh')

def image(invert = False, width=100, height=100):
    imgdata = np.linspace(np.zeros(width),np.ones(width),height)
    rgb = hv.Image(imgdata).opts(
        hv.Options(invert_yaxis=invert)
    )
    return rgb

display(pn.Row(image(False)))
display(pn.Row(image(True)))
display(pn.Row(image(False),image(True)))
```

![Screen Shot 2020-10-31 at 1 06 21 PM](https://user-images.githubusercontent.com/7408243/97785189-e6aca900-1b79-11eb-8177-dc19dd176c2e.png)

**Comment by analog-cbarber** [comment]
Here is the same notebook using Panel 0.9.7
![Screen Shot 2020-10-31 at 1 10 41 PM](https://user-images.githubusercontent.com/7408243/97785299-96821680-1b7a-11eb-8f41-6f82ab171403.png)

**Comment by Hoxbro** [comment]
I think this is gonna be fixed with #4665. I tried to run it and got all of them to show up correctly. 

![Screenshot 2020-10-31 at 21 12 49](https://user-images.githubusercontent.com/19758978/97789095-02d23980-1bbe-11eb-8c8f-8a9d7048a43c.png)

**Comment by kqshan** [comment]
Just FYI: I'm still getting the broken behavior with holoviews 1.14.1 (which I believe is after merging #4665).

Here it is with Panel 0.9.7:
![image](https://user-images.githubusercontent.com/6790411/103392950-1114d700-4ad5-11eb-996b-db3001b267df.png)

and Panel 0.10.2:
![image](https://user-images.githubusercontent.com/6790411/103393195-5dace200-4ad6-11eb-9c3b-4b053f5b65de.png)

**Comment by philippjfr** [comment]
Closing now that Panel 0.10.3 with a fix is released.

**Comment by kgullikson-sc** [comment]
I am still getting the same issue, with the code above, using

* holoviews='1.16.2'
* bokeh='3.1.1'
* panel='1.1.1')

**Comment by philippjfr** [comment]
Please open a new issue, thank you!
