### ISSUE TITLE
Streaming does not work in Notebook with Bokeh 3

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5600]
Follow up to #5388

--- 
_The following is copied (with small changes for clarity) from the issue, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1309286680)._

This does not work in a notebook, but work fine outside it, e.g. when running it with `panel serve`. I suspect the problems are related to `pyviz_comms` but I could be wrong. 

It raises an error when moving the point around.

<details>

<summary>Code</summary>

``` python
import holoviews as hv
from holoviews.streams import PointDraw

hv.extension("bokeh")

points = hv.Points([(0, 0), (0.5, 0.5), (1, 0)])
point_stream = PointDraw(data=points.columns(), source=points)
points.opts(active_tools=["point_draw"])
```
</details>

<details>

<summary>Traceback</summary>

``` python-traceback
Traceback (most recent call last):
  File "/home/shh/miniconda3/envs/bkdev/lib/python3.9/site-packages/pyviz_comms/__init__.py", line 347, in _handle_msg
    self._on_msg(msg)
  File "/home/shh/Repos/bokeh3/panel/panel/viewable.py", line 302, in _on_msg
    patch.apply_to_document(doc, comm.id if comm else None)
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/protocol/messages/patch_doc.py", line 104, in apply_to_document
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/document/callbacks.py", line 405, in invoke_with_curdoc
    return f()
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/protocol/messages/patch_doc.py", line 104, in <lambda>
    invoke_with_curdoc(doc, lambda: doc.apply_json_patch(self.payload, setter=setter))
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/document/document.py", line 373, in apply_json_patch
    patch: PatchJson = deserializer.deserialize(patch_json)
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 491, in deserialize
    return self.decode(obj.content, obj.buffers)
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 506, in decode
    return self._decode(obj)
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 547, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 547, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 549, in _decode
    return [self._decode(entry) for entry in obj]
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 549, in <listcomp>
    return [self._decode(entry) for entry in obj]
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 547, in _decode
    return {key: self._decode(val) for key, val in obj.items()}
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 547, in <dictcomp>
    return {key: self._decode(val) for key, val in obj.items()}
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 528, in _decode
    return self._decode_map(cast(MapRep, obj))
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 579, in _decode_map
    return { self._decode(key): self._decode(val) for key, val in entries }
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 579, in <dictcomp>
    return { self._decode(key): self._decode(val) for key, val in entries }
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 536, in _decode
    return self._decode_ndarray(cast(NDArrayRep, obj))
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 640, in _decode_ndarray
    decoded = self._decode(array)
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 530, in _decode
    return self._decode_bytes(cast(BytesRep, obj))
  File "/home/shh/Repos/bokeh3/bokeh/src/bokeh/core/serialization.py", line 589, in _decode_bytes
    id = data["id"]
KeyError: 'id'
```
</details>

https://user-images.githubusercontent.com/19758978/200924612-804f817b-3d0a-4971-8087-133199ff34b4.mp4

**Comment by philippjfr** [comment]
Hopefully fixed by https://github.com/holoviz/panel/pull/4378

**Comment by Hoxbro** [comment]
https://github.com/holoviz/panel/pull/4378 did not fix this.
