### ISSUE TITLE
Holoviews widget does not work in Bokeh 3

### ISSUE THREAD

**Issue by Hoxbro** [holoviz/holoviews#5601]
Follow up to #5388

--- 
_The following is copied (with small changes for clarity) from the issue, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1309286680)._

This does not work in a notebook, but work fine outside it, e.g. when running it with `panel serve`. I suspect the problems are related to `pyviz_comms` but I could be wrong. 

The widget does not update the plot and gives an error in the console. A minor note is the formatting around the widget seems to be gone when compared to the previous version of holoviews/bokeh.

 

<details>

<summary>Code</summary>

``` python
import pandas as pd
import numpy as np
import holoviews as hv
import panel as pn

hv.extension("bokeh")

df = pd.DataFrame(np.random.randint(0, 10, size=(100, 3)), columns=list("ABC"))
ds = hv.Dataset(df, ['A', "B"], ["C"])
ds.aggregate(function=np.mean).to(hv.Scatter, 'A', 'C')

```
</details>

<details>

<summary>Console</summary>

``` console
Uncaught TypeError: e is undefined
    apply_state http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:1669
    set_state http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:1669
    anonymous http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript line 596 > Function:13
    execute http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:596
    n http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:359
    emit http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:323
    emit http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:323
    _setv http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    setv http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    set http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    _slide http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:978
    render http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:978
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    ut http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    ut http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    Z http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    o http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
Untitled.ipynb line 2 > injectedScript:1669:342
    apply_state http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:1669
    set_state http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:1669
    anonymous http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript line 596 > Function:13
    execute http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:596
    n http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:359
    emit http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:323
    emit http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:323
    _setv http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    setv http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    set http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:322
    _slide http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:978
    render http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:978
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    forEach self-hosted:203
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    forEach self-hosted:203
    st http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    ut http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    forEach self-hosted:203
    ut http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    Z http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979
    o http://localhost:8888/lab/tree/Untitled.ipynb line 2 > injectedScript:979

```
</details>

<details>

<summary>Previous version layout</summary>

![image](https://user-images.githubusercontent.com/19758978/200926755-bdee9b2e-63b3-4ad7-8078-55b647e33c5d.png)

</details>

https://user-images.githubusercontent.com/19758978/200925588-1c779ce8-4aa9-4ec1-b3dd-8b925bb253f5.mp4

---

Comment from @philippjfr, [ref](https://github.com/holoviz/holoviews/pull/5388#issuecomment-1400088175).

> Will need investigation. The formatting will be restored when we finish the CSS PR and add WidgetBox styles correctly.

**Comment by philippjfr** [comment]
Hopefully fixed by https://github.com/holoviz/panel/pull/4378

**Comment by Hoxbro** [comment]
https://github.com/holoviz/panel/pull/4378 did not fix this, though I'm getting a new console error:

``` console
Uncaught Error: Expected binary fragment but received text fragment
    _assume_binary http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:371
    _BUFFER_PAYLOAD http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:371
    consume http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:371
    apply_state http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:1642
    set_state http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:1642
    anonymous http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript line 597 > Function:13
    execute http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:597
    n http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:359
    emit http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:323
    emit http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:323
    _setv http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:322
    setv http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:322
    set http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:322
    _slide http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:979
    render http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:979
    st http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    st http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    st http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    ut http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    ut http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    Z http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
    o http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb line 2 > injectedScript:980
16 [Untitled4.ipynb line 2 > injectedScript:371:1107](http://localhost:8888/lab/workspaces/auto-g/tree/Untitled4.ipynb%20line%202%20%3E%20injectedScript)
```

**Comment by Hoxbro** [comment]
Fixed by: https://github.com/holoviz/panel/pull/4634
